"""add email to user

Revision ID: 655923af14a9
Revises: c14e948d039f
Create Date: 2025-05-24 11:47:47.142718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655923af14a9'
down_revision = 'c14e948d039f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
