"""initial tables

Revision ID: c5491daff108
Revises: b35b8f233d92
Create Date: 2025-05-25 20:50:13.917393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5491daff108'
down_revision = 'b35b8f233d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
