"""add user and book relationship

Revision ID: 96fa4ba57fbe
Revises: 80e77866072a
Create Date: 2025-05-26 12:15:18.040757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fa4ba57fbe'
down_revision = '80e77866072a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
