"""update bookstatus

Revision ID: 8afd2ace1819
Revises: 013eafcfdfc9
Create Date: 2025-05-26 13:01:54.503663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afd2ace1819'
down_revision = '013eafcfdfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('jti', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
