"""ubah enum BookStatus format final

Revision ID: 48e3e7ab4bc1
Revises: 5fa7943e4030
Create Date: 2025-05-23 20:13:38.447736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48e3e7ab4bc1'
down_revision = '5fa7943e4030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('Want to Read', 'Reading', 'Finished', name='bookstatus'),
               nullable=False,
               existing_server_default=sa.text("'Want to Read'::bookstatus"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('Want to Read', 'Reading', 'Finished', name='bookstatus'),
               nullable=True,
               existing_server_default=sa.text("'Want to Read'::bookstatus"))
    # ### end Alembic commands ###
