"""Add user_id to books

Revision ID: 013eafcfdfc9
Revises: 96fa4ba57fbe
Create Date: 2025-05-26 12:41:28.601447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013eafcfdfc9'
down_revision = '96fa4ba57fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
