"""ubah enum BookStatus

Revision ID: 5fa7943e4030
Revises: 340f60e9847d
Create Date: 2025-05-23 19:19:37.156350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa7943e4030'
down_revision = '340f60e9847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
