"""update models book user

Revision ID: e229cf4ec1b3
Revises: 1dda59340793
Create Date: 2025-05-26 10:32:07.018610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e229cf4ec1b3'
down_revision = '1dda59340793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='revoked_tokens_pkey'),
    sa.UniqueConstraint('jti', name='revoked_tokens_jti_key')
    )
    # ### end Alembic commands ###
