"""Add status field with BookStatus enum to books

Revision ID: e35c0d545737
Revises: f607e1291b0a
Create Date: 2025-05-26 20:25:56.668422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35c0d545737'
down_revision = 'f607e1291b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('jti', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
