"""Add status field with BookStatus enum to books

Revision ID: 31aad30930ec
Revises: 8afd2ace1819
Create Date: 2025-05-26 19:01:56.768965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31aad30930ec'
down_revision = '8afd2ace1819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('jti', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
