"""Add revoked_tokens table

Revision ID: c14e948d039f
Revises: 64bd66bc1a99
Create Date: 2025-05-24 10:11:01.819773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14e948d039f'
down_revision = '64bd66bc1a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
