"""create users table

Revision ID: 64bd66bc1a99
Revises: 612ad27c4028
Create Date: 2025-05-24 01:13:01.154679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64bd66bc1a99'
down_revision = '612ad27c4028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
