"""update book

Revision ID: e5b286578397
Revises: a7fabd75eca5
Create Date: 2025-05-27 20:05:05.531872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b286578397'
down_revision = 'a7fabd75eca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    op.add_column('books', sa.Column('isbn', sa.String(length=255), nullable=True))
    op.drop_constraint('books_openlibrary_id_key', 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.drop_column('books', 'openlibrary_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('openlibrary_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint('books_openlibrary_id_key', 'books', ['openlibrary_id'])
    op.drop_column('books', 'isbn')
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('jti', name='revoked_tokens_pkey')
    )
    # ### end Alembic commands ###
