"""ubah enum BookStatus tanpa spasi

Revision ID: 612ad27c4028
Revises: 48e3e7ab4bc1
Create Date: 2025-05-23 20:19:03.610363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612ad27c4028'
down_revision = '48e3e7ab4bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
